CREATE TABLE dkmn_akta_notaris (
    id              int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd         int4 NOT NULL,
    nomor           varchar(100) NOT NULL DEFAULT ''::character varying,
    notaris         varchar(100) NOT NULL DEFAULT ''::character varying,
    tanggal         date NOT NULL,
    keterangan      text NOT NULL DEFAULT '',
    file            text NOT NULL DEFAULT '',
    created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      int4 NOT NULL DEFAULT 0,
    updated_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by      int4 NOT NULL DEFAULT 0,
    deleted_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by      int4 NOT NULL DEFAULT 0,
    CONSTRAINT dkmn_akta_notaris_pkey PRIMARY KEY (id)
);

-- Add foreign key constraint to bumd table
ALTER TABLE dkmn_akta_notaris 
ADD CONSTRAINT fk_dkmn_akta_notaris_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add indexes for better performance
CREATE INDEX idx_dkmn_akta_notaris_id_bumd 
    ON dkmn_akta_notaris(id_bumd);

CREATE INDEX idx_dkmn_akta_notaris_nomor_perda 
    ON dkmn_akta_notaris(nomor_perda);

CREATE INDEX idx_dkmn_akta_notaris_tanggal_perda 
    ON dkmn_akta_notaris(tanggal_perda);

CREATE INDEX idx_dkmn_akta_notaris_deleted_at 
    ON dkmn_akta_notaris(deleted_at);