CREATE TABLE mst_jenis_dokumen (
    id              int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    nama            varchar(250) NOT NULL DEFAULT ''::character varying,
    deskripsi       text NOT NULL DEFAULT '',
    created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      int4 NOT NULL DEFAULT 0,
    updated_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by      int4 NOT NULL DEFAULT 0,
    deleted_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by      int4 NOT NULL DEFAULT 0,
    CONSTRAINT mst_jenis_dokumen_pkey PRIMARY KEY (id)
);

-- Populate data
INSERT INTO mst_jenis_dokumen (nama, deskripsi, created_by) VALUES
('SOP', '', 1),
('Dokumen Tata Kelola', '', 1),
('Pengadaan Barang Jasa', '', 1),
('Kerjasama / SPK', '', 1),
('Pinjaman', '', 1),
('Rencana Bisnis', '', 1),
('Rencana Kerja Anggaran', '', 1);