CREATE TABLE dkmn_perda_pendirian (
    id              int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd         int4 NOT NULL,
    nomor           varchar(100) NOT NULL DEFAULT ''::character varying,
    tanggal         date NOT NULL,
    modal_dasar     float8 NOT NULL DEFAULT 0,
    keterangan      text NOT NULL DEFAULT '',
    file            text NOT NULL DEFAULT '',
    created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      int4 NOT NULL DEFAULT 0,
    updated_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by      int4 NOT NULL DEFAULT 0,
    deleted_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by      int4 NOT NULL DEFAULT 0,
    CONSTRAINT dkmn_perda_pendirian_pkey PRIMARY KEY (id)
);

-- Add foreign key constraint to bumd table
ALTER TABLE dkmn_perda_pendirian 
ADD CONSTRAINT fk_dkmn_perda_pendirian_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add indexes for better performance
CREATE INDEX idx_dkmn_perda_pendirian_id_bumd 
    ON dkmn_perda_pendirian(id_bumd);

CREATE INDEX idx_dkmn_perda_pendirian_nomor
    ON dkmn_perda_pendirian(nomor);

CREATE INDEX idx_dkmn_perda_pendirian_tanggal 
    ON dkmn_perda_pendirian(tanggal);

CREATE INDEX idx_dkmn_perda_pendirian_deleted_at 
    ON dkmn_perda_pendirian(deleted_at);