CREATE TABLE users (
    id          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    username    varchar(200) NOT NULL DEFAULT ''::character varying,
    password    varchar(150) NOT NULL DEFAULT ''::character varying,
    id_daerah   int4 NOT NULL DEFAULT 0,
    id_role     int4 NOT NULL DEFAULT 0,
    id_bumd     int4 NOT NULL DEFAULT 0,
    nama        varchar(250) NOT NULL DEFAULT ''::character varying,
    logo        text NOT NULL DEFAULT '',
    created_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  int4 NOT NULL DEFAULT 0,
    updated_at  timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by  int4 NOT NULL DEFAULT 0,
    deleted_at  timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by  int4 NOT NULL DEFAULT 0,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- Populate data
INSERT INTO users (username, password, id_role, nama) VALUES
('admin', '$2a$12$c1oTnbMoQM/VuwAW2xXNhehGlTecToWCyfF1gKiv0wFg47BAc0abu', 1, 'Admin Pusat');

-- Add foreign key constraint to roles table
ALTER TABLE users 
ADD CONSTRAINT fk_users_id_role 
FOREIGN KEY (id_role) REFERENCES roles(id);

-- Add foreign key constraint to bumd table
ALTER TABLE users 
ADD CONSTRAINT fk_users_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add unique constraint to username
ALTER TABLE users 
ADD CONSTRAINT unique_users_username 
UNIQUE (username);

-- Add indexes for better performance
CREATE INDEX idx_users_username 
    ON users(username);

CREATE INDEX idx_users_id_daerah 
    ON users(id_daerah);

CREATE INDEX idx_users_id_bumd 
    ON users(id_bumd);

CREATE INDEX idx_users_id_role 
    ON users(id_role);

CREATE INDEX idx_users_deleted_at 
    ON users(deleted_at);