CREATE TABLE m_pendidikan (
    id_pendidikan       int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    nama_pendidikan     varchar(255) NOT NULL DEFAULT ''::character varying,
    created_at          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          int4 NOT NULL DEFAULT 0,
    updated_at          timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by          int4 NOT NULL DEFAULT 0,
    deleted_at          timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by          int4 NOT NULL DEFAULT 0,
    CONSTRAINT m_pendidikan_pkey PRIMARY KEY (id_pendidikan)
);

CREATE INDEX idx_m_pendidikan_nama_pendidikan ON m_pendidikan(nama_pendidikan);

-- Populate data
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('SD (Sekolah Dasar) dan Sederajat', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('SMP (Sekolah Menengah Pertama) dan Sederajat', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('SMA (Sekolah Menengah Atas) dan Sederajat', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('SMK (Sekolah Menengah Kejuruan) dan Sederajat', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('D1', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('D2', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('D3 (Ahli Madya)', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('D4 (Sarjana Terapan)', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('S1 (Sarjana)', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('S2 (Magister)', 1, 1, 1);
INSERT INTO m_pendidikan (nama_pendidikan, created_by, updated_by, deleted_by) VALUES ('S3 (Doktor)', 1, 1, 1);
