CREATE TABLE roles (
    id          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    nama        varchar(250) NOT NULL DEFAULT ''::character varying,
    created_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  int4 NOT NULL DEFAULT 0,
    updated_at  timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by  int4 NOT NULL DEFAULT 0,
    deleted_at  timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by  int4 NOT NULL DEFAULT 0,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

-- Add index on nama for better search performance
CREATE INDEX idx_roles_nama
    ON roles(nama);

-- Add index on deleted_at for soft delete queries
CREATE INDEX idx_roles_deleted_at 
    ON roles(deleted_at);

-- Populate data
INSERT INTO roles (nama, created_by) VALUES
('Admin Pusat', 0),
('Admin Daerah', 1),
('BUMD', 2);