CREATE TABLE sys_config (
    id                          int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    otp_expired_minutes         int4 NOT NULL DEFAULT 5,
    jwt_expired_minutes         int4 NOT NULL DEFAULT 480,
    refresh_token_expired_hour  int4 NOT NULL DEFAULT 336,
    CONSTRAINT sys_config_pkey PRIMARY KEY (id)
);

INSERT INTO sys_config(otp_expired_minutes, jwt_expired_minutes, refresh_token_expired_hour) VALUES (5,3600,2000);