CREATE TABLE keu_laporan (
    id                  int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd             int4 NOT NULL DEFAULT 0,
    id_parlapbumd       int4 NOT NULL DEFAULT 0,
    id_itemkeu          int4 NOT NULL DEFAULT 0,
    tahun               int4 NOT NULL DEFAULT 0,
    jumlah              float8 NOT NULL DEFAULT 0,
    file                text NOT NULL DEFAULT ''::text,
    created_at          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          int4 NOT NULL DEFAULT 0,
    updated_at          timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by          int4 NOT NULL DEFAULT 0,
    deleted_at          timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by          int4 NOT NULL DEFAULT 0,
    CONSTRAINT keu_laporan_pkey PRIMARY KEY (id)
);

-- Add foreign key constraint to bumd table
ALTER TABLE keu_laporan 
ADD CONSTRAINT fk_keu_laporan_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add foreign key constraint to parlapbumd table
ALTER TABLE keu_laporan 
ADD CONSTRAINT fk_keu_laporan_id_parlapbumd
FOREIGN KEY (id_parlapbumd) REFERENCES parlapbumd(id);
