CREATE TABLE keu_modal (
    id                  int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd             int4 NOT NULL,
    id_prov             int4 NOT NULL DEFAULT 0,
    id_kab              int4 NOT NULL DEFAULT 0,
    pemegang            varchar(100) NOT NULL DEFAULT ''::character varying,
    no_ba               varchar(100) NOT NULL DEFAULT ''::character varying,
    tanggal             date NOT NULL,
    jumlah              float8 NOT NULL DEFAULT 0,
    keterangan          text NOT NULL DEFAULT ''::text,
    created_at          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          int4 NOT NULL DEFAULT 0,
    updated_at          timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by          int4 NOT NULL DEFAULT 0,
    deleted_at          timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by          int4 NOT NULL DEFAULT 0,
    CONSTRAINT keu_modal_pkey PRIMARY KEY (id)
);

-- Add foreign key constraint to bumd table
ALTER TABLE keu_modal 
ADD CONSTRAINT fk_keu_modal_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add indexes for better performance
CREATE INDEX idx_keu_modal_id_bumd 
    ON keu_modal(id_bumd);
    