CREATE TABLE bumd (
    id              int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_daerah       int4 NOT NULL DEFAULT 0,
    id_bentuk_hukum int4 NOT NULL DEFAULT 0,
    id_bentuk_usaha int4 NOT NULL DEFAULT 0,
    id_induk_perusahaan int4 NOT NULL DEFAULT 0,
    penerapan_spi   boolean NOT NULL DEFAULT false,
    file_spi        text NOT NULL DEFAULT '',
    nama            varchar(250) NOT NULL DEFAULT ''::character varying,
    deskripsi       text NOT NULL DEFAULT '',
    alamat          text NOT NULL DEFAULT '',
    no_telp         varchar(30) NOT NULL DEFAULT ''::character varying,
    no_fax          varchar(30) NOT NULL DEFAULT ''::character varying,
    email           varchar(250) NOT NULL DEFAULT ''::character varying,
    website         varchar(250) NOT NULL DEFAULT ''::character varying,
    narahubung      varchar(30) NOT NULL DEFAULT ''::character varying,
    npwp            varchar(20) NOT NULL DEFAULT ''::character varying,
    npwp_pemberi    varchar(250) NOT NULL DEFAULT ''::character varying,
    npwp_file       text NOT NULL DEFAULT '',
    logo            text NOT NULL DEFAULT '',
    created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      int4 NOT NULL DEFAULT 0,
    updated_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by      int4 NOT NULL DEFAULT 0,
    deleted_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by      int4 NOT NULL DEFAULT 0,
    CONSTRAINT bumd_pkey PRIMARY KEY (id)
);

-- Add foreign key constraints
ALTER TABLE bumd 
ADD CONSTRAINT fk_bumd_id_bentuk_hukum 
FOREIGN KEY (id_bentuk_hukum) REFERENCES mst_bentuk_badan_hukum(id);

ALTER TABLE bumd 
ADD CONSTRAINT fk_bumd_id_bentuk_usaha 
FOREIGN KEY (id_bentuk_usaha) REFERENCES mst_bentuk_usaha(id);

-- Add indexes for better performance
CREATE INDEX idx_bumd_id_daerah 
    ON bumd(id_daerah);

CREATE INDEX idx_bumd_id_bentuk_hukum 
    ON bumd(id_bentuk_hukum);

CREATE INDEX idx_bumd_id_bentuk_usaha 
    ON bumd(id_bentuk_usaha);

CREATE INDEX idx_bumd_id_induk_perusahaan 
    ON bumd(id_induk_perusahaan);

CREATE INDEX idx_bumd_penerapan_spi 
    ON bumd(penerapan_spi);

CREATE INDEX idx_bumd_nama 
    ON bumd(nama);

CREATE INDEX idx_bumd_deleted_at 
    ON bumd(deleted_at);