CREATE TABLE trn_produk (
    id_produk               int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd                 int4 NOT NULL DEFAULT 0,
    nama_produk             varchar(255) NOT NULL DEFAULT '',
    deskripsi               text NOT NULL DEFAULT '',
    foto_produk             text NOT NULL DEFAULT '',
    created_at              timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              int4 NOT NULL DEFAULT 0,
    updated_at              timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by              int4 NOT NULL DEFAULT 0,
    deleted_at              timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by              int4 NOT NULL DEFAULT 0,
    CONSTRAINT trn_produk_pkey PRIMARY KEY (id_produk)
);

ALTER TABLE trn_produk ADD CONSTRAINT trn_produk_id_bumd_fk FOREIGN KEY (id_bumd) REFERENCES bumd(id);

CREATE INDEX idx_trn_produk_id_bumd ON trn_produk(id_bumd);
CREATE INDEX idx_trn_produk_nama_produk ON trn_produk(nama_produk);
CREATE INDEX idx_trn_produk_deskripsi ON trn_produk(deskripsi);
CREATE INDEX idx_trn_produk_foto_produk ON trn_produk(foto_produk);