CREATE TABLE dkmn_nib (
    id                 int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd            int4 NOT NULL,
    nomor              varchar(100) NOT NULL DEFAULT ''::character varying,
    instansi_pemberi   varchar(250) NOT NULL DEFAULT ''::character varying,
    tanggal            date NOT NULL,
    kualifikasi        int4 NOT NULL DEFAULT 0,
    klasifikasi        varchar(100) NOT NULL DEFAULT ''::character varying,
    masa_berlaku       date NULL,
    file               text NOT NULL DEFAULT '',
    created_at         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         int4 NOT NULL DEFAULT 0,
    updated_at         timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by         int4 NOT NULL DEFAULT 0,
    deleted_at         timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by         int4 NOT NULL DEFAULT 0,
    CONSTRAINT dkmn_nib_pkey PRIMARY KEY (id)
);

-- Add foreign key constraint to bumd table
ALTER TABLE dkmn_nib 
ADD CONSTRAINT fk_dkmn_nib_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add indexes for better performance
CREATE INDEX idx_dkmn_nib_id_bumd 
    ON dkmn_nib(id_bumd);

CREATE INDEX idx_dkmn_nib_nomor 
    ON dkmn_nib(nomor);

CREATE INDEX idx_dkmn_nib_tanggal 
    ON dkmn_nib(tanggal);

CREATE INDEX idx_dkmn_nib_masa_berlaku 
    ON dkmn_nib(masa_berlaku);

CREATE INDEX idx_dkmn_nib_deleted_at 
    ON dkmn_nib(deleted_at);