CREATE TABLE mst_bentuk_usaha (
    id              int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    nama            varchar(250) NOT NULL DEFAULT ''::character varying,
    deskripsi       text NOT NULL DEFAULT '',
    created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      int4 NOT NULL DEFAULT 0,
    updated_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by      int4 NOT NULL DEFAULT 0,
    deleted_at      timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by      int4 NOT NULL DEFAULT 0,
    CONSTRAINT mst_bentuk_usaha_pkey PRIMARY KEY (id)
);

-- Add index on nama for better search performance
CREATE INDEX idx_mst_bentuk_usaha_nama 
    ON mst_bentuk_usaha(nama);

-- Add index on deleted_at for soft delete queries
CREATE INDEX idx_mst_bentuk_usaha_deleted_at 
    ON mst_bentuk_usaha(deleted_at);

-- Populate data
INSERT INTO mst_bentuk_usaha (nama, deskripsi, created_by) VALUES
('Air Minum', '', 1),
('Aneka Usaha', '', 1),
('BPD', '', 1),
('BPR', '', 1),
('JAMKRIDA', '', 1),
('Pasar', '', 1),
('Lainnya', '', 1),
('Migas', '', 1),
('Pariwisata', '', 1),
('MINERBA', '', 1),
('AGRO', '', 1),
('Kepelabuhan', '', 1),
('Transportasi', '', 1);