CREATE TABLE trn_pengurus (
    id_pengurus             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd                 int4 NOT NULL DEFAULT 0,
    jabatan_struktur        int4 NOT NULL DEFAULT 0,
    nama_pengurus           varchar(255) NOT NULL DEFAULT '',
    nik                     varchar(255) NOT NULL DEFAULT '',
    alamat                  varchar(255) NOT NULL DEFAULT '',
    deskripsi_jabatan       text NOT NULL DEFAULT '',
    pendidikan_akhir        int4 NOT NULL DEFAULT 0,
    tanggal_mulai_jabatan   date NOT NULL DEFAULT '0001-01-01',
    tanggal_akhir_jabatan   date NOT NULL DEFAULT '0001-01-01',
    file                    text NOT NULL DEFAULT '',
    created_at              timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              int4 NOT NULL DEFAULT 0,
    updated_at              timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by              int4 NOT NULL DEFAULT 0,
    deleted_at              timestamp NOT NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by              int4 NOT NULL DEFAULT 0,
    CONSTRAINT trn_pengurus_pkey PRIMARY KEY (id_pengurus)
);

-- Add foreign key constraint to bumd table
ALTER TABLE trn_pengurus ADD CONSTRAINT trn_pengurus_id_bumd_fk FOREIGN KEY (id_bumd) REFERENCES bumd(id);
ALTER TABLE trn_pengurus ADD CONSTRAINT trn_pengurus_pendidikan_akhir_fk FOREIGN KEY (pendidikan_akhir) REFERENCES m_pendidikan(id_pendidikan);

-- Create index
CREATE INDEX idx_trn_pengurus_id_bumd ON trn_pengurus(id_bumd);
CREATE INDEX idx_trn_pengurus_jabatan_struktur ON trn_pengurus(jabatan_struktur);
CREATE INDEX idx_trn_pengurus_nama_pengurus ON trn_pengurus(nama_pengurus);
CREATE INDEX idx_trn_pengurus_nik ON trn_pengurus(nik);