CREATE TABLE trn_rka (
    id                 int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    id_bumd            int4 NOT NULL,
    nomor              varchar(100) NOT NULL DEFAULT ''::character varying,
    instansi_pemberi   varchar(250) NOT NULL DEFAULT ''::character varying,
    tanggal            date NOT NULL,
    kualifikasi        int4 NOT NULL DEFAULT 0,
    klasifikasi        varchar(100) NOT NULL DEFAULT ''::character varying,
    masa_berlaku       date NULL,
    file               text NOT NULL DEFAULT '',
    created_at         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         int4 NOT NULL DEFAULT 0,
    updated_at         timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    updated_by         int4 NOT NULL DEFAULT 0,
    deleted_at         timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
    deleted_by         int4 NOT NULL DEFAULT 0,
    CONSTRAINT trn_rka_pkey PRIMARY KEY (id)
);

-- Add foreign key constraint to bumd table
ALTER TABLE trn_rka 
ADD CONSTRAINT fk_trn_rka_id_bumd 
FOREIGN KEY (id_bumd) REFERENCES bumd(id);

-- Add indexes for better performance
CREATE INDEX idx_trn_rka_id_bumd 
    ON trn_rka(id_bumd);

CREATE INDEX idx_trn_rka_nomor 
    ON trn_rka(nomor);

CREATE INDEX idx_trn_rka_tanggal 
    ON trn_rka(tanggal);

CREATE INDEX idx_trn_rka_masa_berlaku 
    ON trn_rka(id_bumd);